In [1]:
import numpy as np

In [2]:
arr=np.zeros((3,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
arr=np.zeros((3,3),dtype=int)

r=np.random.randint(0,3)
c=np.random.randint(0,3)

arr[r,c]=  20
row=int(input("enter row"))
col=int(input('enter col'))
if arr[row,col]==20:
    print('you won')
else:
    print('try again')


print(arr)

try again
[[ 0  0 20]
 [ 0  0  0]
 [ 0  0  0]]
